using System.Text.RegularExpressions;

namespace WorkPlanStudio.Web.Tests;

/// <summary>
/// The host page is the one file no unit or component test renders, so a dead
/// reference in it fails silently: the browser logs a 404 and carries on. This
/// caught a leftover <c>WorkPlanStudio.styles.css</c> link - the scoped-CSS
/// bundle Blazor only emits when a project has <c>.razor.css</c> files, which
/// this one does not, so every page load 404'd in production.
/// </summary>
public class StaticAssetTests
{
    private static readonly Regex AssetReference =
        new(@"(?:src|href)=""(?!https?:|data:|#)(?<path>[^""]+)""", RegexOptions.Compiled);

    [Fact]
    public void Every_asset_the_host_page_links_is_actually_shipped()
    {
        var wwwroot = RepoFiles.AppWwwroot;
        var html = File.ReadAllText(Path.Join(wwwroot, "index.html"));

        var missing = AssetReference.Matches(html)
            .Select(match => match.Groups["path"].Value)
            // "/" is the <base href> and "." is the reload link; both are routes,
            // not files. _framework is generated by the build, not committed.
            .Where(path => path is not "/" and not "." && !path.StartsWith("_framework/", StringComparison.Ordinal))
            .Distinct(StringComparer.Ordinal)
            .Where(path => !File.Exists(Path.Join(wwwroot, path.Replace('/', Path.DirectorySeparatorChar))))
            .ToArray();

        Assert.True(missing.Length == 0, "index.html links assets that do not exist: " + string.Join(", ", missing));
    }

    [Fact]
    public void The_host_page_declares_a_content_security_policy_that_stays_same_origin()
    {
        var html = File.ReadAllText(Path.Join(RepoFiles.AppWwwroot, "index.html"));

        var policy = Regex.Match(html, @"http-equiv=""Content-Security-Policy""\s+content=""(?<policy>[^""]*)""",
            RegexOptions.Singleline).Groups["policy"].Value;
        policy = Regex.Replace(policy, @"\s+", " ").Trim();

        Assert.Contains("default-src 'none'", policy, StringComparison.Ordinal);
        Assert.Contains("base-uri 'self'", policy, StringComparison.Ordinal);
        Assert.Contains("form-action 'none'", policy, StringComparison.Ordinal);

        // 'wasm-unsafe-eval' and inline script are load-bearing (see the comment
        // in index.html); a wildcard script source would not be.
        Assert.DoesNotContain("script-src * ", policy + " ", StringComparison.Ordinal);
        Assert.DoesNotContain("'unsafe-eval'", policy.Replace("'wasm-unsafe-eval'", "", StringComparison.Ordinal), StringComparison.Ordinal);
    }
}
